import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { collection, query, getDocs,  where, onSnapshot, orderBy } from 'firebase/firestore';
import { auth, db } from '../../firebase';
import Head from "next/head";
import Sidebar from '../../components/National/Sidebar';
import { ArrowLeftIcon, HomeIcon, MenuAlt1Icon, SearchIcon } from "@heroicons/react/outline";
import Widgets from '../../components/County/Widgets';
import CommentModal from '../../components/County/CommentModal';
import CountyTrends from '../../components/County/CountyTrends';
import { Button, Spinner, Tooltip } from 'flowbite-react';

export default function TopicPostsPage() {
  const router = useRouter();
  const { topic } = router.query;
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [userData, setUserData] = useState(null);
  const [userDetails, setUserDetails] = useState(null);
  const [isSidebarVisible, setIsSidebarVisible] = useState(false);
  const [isWidgetsVisible, setIsWidgetsVisible] = useState(false);
  

  const fetchUserData = async () => {
    auth.onAuthStateChanged(async (user) => {
      console.log(user)
      setUserDetails(user)

    })
  }

  useEffect(() => {
    fetchUserData();
  }, []);

  useEffect(() => {
    const fetchUserData = async () => {
      if (userDetails) {
        const q = query(collection(db, 'userPosts'), where('id', '==', userDetails.uid));
        const querySnapshot = await getDocs(q);

        if (!querySnapshot.empty) {
          setUserData(querySnapshot.docs[0].data());
        }
      }
    };

    fetchUserData();
  }, [userDetails]);

  useEffect(() => {
    if (!userData || !userData.county) {
      setLoading(true);
      return;
    }
  
    const q = query(collection(db, "county", userData.county), orderBy('timestamp', 'desc'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const filteredPosts = snapshot.docs
        .filter(doc => {
          const data = doc.data();
          return data.text && data.text.includes(topic);
        })
        
      setPosts(filteredPosts);
      setLoading(false);
    });
  
    return () => unsubscribe();
  }, [userData, topic]);
  
  const toggleSidebar = () => {
    setIsSidebarVisible(!isSidebarVisible);
  };

  const toggleWidgets = () => {
    setIsWidgetsVisible(!isWidgetsVisible);
  }

  const toggleHome = () => {
    setIsWidgetsVisible(false);
    setIsSidebarVisible(false);
  }


  return (
    <div>
      <Head>
        <title>{topic ?  topic : 'loading...'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../../images/Brod.png" />
      </Head>
      <main className="flex min-h-screen mx-auto dark:bg-gray-950 sm:w-screen min-w-[580px] flex-grow sm:px-10 md:px-24 xl:px-0">
        {/* Sidebar */}
        {isSidebarVisible && (
              <div
                className="fixed inset-0 z-30 bg-black bg-opacity-50 xl:hidden"
                onClick={() => setIsSidebarVisible(false)}
              >
                <div
                  onClick={(e) => e.stopPropagation()} // Prevents the click event from closing the sidebar when clicked inside it
                >
                  <Sidebar />
                </div>
              </div>
            )}
        <div className='hidden xl:inline'>
        <Sidebar />
        </div>
        {/* Feed */}
        <div className="xl:ml-[370px] xl:min-w-[576px]  sm:min-w-full flex-grow max-w-xl">
          <div className="flex items-center space-x-2  py-2 px-3 sticky top-0 bg-white dark:bg-gray-950 border-[1px] rounded-md border-gray-300 dark:border-gray-900">
          <Tooltip content='back' arrow={false} placement="bottom" className="p-1 text-xs bg-gray-500 -mt-1">
            
            <div className="animate-pulse" onClick={() => router.replace("/county")}>
              <ArrowLeftIcon className="h-8 cursor-pointer animate-pulse" />
            </div>
          </Tooltip>
            <h2 className="text-lg  font-bold cursor-pointer">
            {topic ? (topic):(loading && <Spinner size="sm" />)}
            </h2>
          </div>
          {loading ? (<Button color="gray" className="border-0">
                      <Spinner aria-label="Alternate spinner button example" size="sm" />
                      <span className="pl-3">Loading...</span>
                    </Button>) :(
                     
            <div>
              {posts.map((post) => (
               <div key={post.id}>
                 <CountyTrends  key={post.id} id={post.id} post={post}/>
               </div>
              ))}
            </div>
          )}
        </div>
        {isWidgetsVisible && (
          <div className="fixed inset-0 z-30  bg-black bg-opacity-50 xl:hidden" onClick={() => setIsWidgetsVisible(false)}>
          <div
                  onClick={(e) => e.stopPropagation()} // Prevents the click event from closing the sidebar when clicked inside it
                >
            <Widgets />
            </div>
          </div>
        )}
       <div className='hidden xl:inline'>
       <Widgets />
       </div>
        
        <CommentModal />
      </main>
      <div className='xl:hidden justify-between bottom-0 z-40 sticky bg-slate-50
       dark:bg-neutral-700 sm:w-screen min-w-[580px] flex p-2  sm:px-10 md:px-24 px-4 flex-grow'>
          <MenuAlt1Icon className='pl-4 h-8 cursor-pointer' onClick={toggleSidebar} />
          <HomeIcon className='h-8 cursor-pointer' onClick={toggleHome}/>
          <SearchIcon className='pr-6 h-8 cursor-pointer' onClick={toggleWidgets}/>
      </div>
    </div>
  );
}
